### ISSUE TITLE
XPathMacFilter规则存在没法翻页的bug

### ISSUE THREAD

**Issue by zhixc** [FongMi/CatVodSpider#10]
&nbsp;&nbsp;尊敬的作者，您好。

&nbsp;&nbsp;我在使用您的 jar 包搭配我用XPath语法写的一个视频源，测试时发现，没有办法翻页，作者大大有空的时候看看能不能修复。还有播放页面的视频【布雷蓝光】线路的可以播放，而【非凡资源】线路不能播放，这种情况有没有办法给XPath类增强一下？

&nbsp;&nbsp;这是我使用的接口配置文件：https://raw.githubusercontent.com/zhixc/tvbox/main/v2.json

&nbsp;&nbsp;在此感谢您了。

**Comment by FongMi** [comment]
因為你不是用影視APP，所以無法翻頁。
非凡资源 檢查一下是否需要 referer，目前也有支持 playReferer。
