### ISSUE TITLE
How to create the VOD link to the TV app?

### ISSUE THREAD

**Issue by kentanttw** [FongMi/CatVodSpider#24]
{
    "key":"dr_爱壹帆",
    "name":"爱壹帆(drpy)",
    "type":3,
    "api":"https://ghproxy.liuzhicong.com/https://raw.githubusercontent.com/hjdhnx/dr_py/main/libs/drpy2.min.js",
    "searchable":2,
    "quickSearch":0,
    "filterable":1,
    "ext":"https://ghproxy.liuzhicong.com/https://raw.githubusercontent.com/hjdhnx/dr_py/main/js/%E7%88%B1%E5%A3%B9%E5%B8%86.js"
},

**Comment by FongMi** [comment]
請參考範例
https://github.com/FongMi/CatVodSpider/blob/main/json/config.json

**Comment by kentanttw** [comment]
Hi, I have edited the json link you send me but could not save the edited file online properly. Any suggestions to save the edited file online properly for use?

**Comment by FongMi** [comment]
放在自己的伺服器或是github
