### ISSUE TITLE
miss显示更多分类

### ISSUE THREAD

**Issue by leftjs** [FongMi/CatVodSpider#25]
展示排行榜之类，是否可以去除筛选

https://github.com/FongMi/CatVodSpider/blob/0a6e7013c0fadacb3288864178d09b849d6c20c4/app/src/main/java/com/github/catvod/spider/Miss.java#L36

**Comment by FongMi** [comment]
等你PR

**Comment by leftjs** [comment]
approve PR #26 , plz @FongMi    

> 等你PR
