### ISSUE TITLE
alist如果server带路径则无法获取数据

### ISSUE THREAD

**Issue by JamesSun-LR** [FongMi/CatVodSpider#36]
alist如果server带路径，路径里含有“/”，可能是认为路径是目录

**Comment by FongMi** [comment]
![image](https://github.com/FongMi/CatVodSpider/assets/3471963/b9523939-e570-4dc2-af89-d2a9ee8cbc81)

**Comment by JamesSun-LR** [comment]
@FongMi  是这样的，我的的alist服务配置了  "site_url": “alist”
在访问时，需要加路径：比如http://0.0.0.0:5244/alist/阿里云盘， 这边tvbox调用alist api获取列表时，可能认为alist是个目录，但是实际是server的site_url

**Comment by FongMi** [comment]
了解，這樣爬蟲就不適用了。
